### ISSUE TITLE
Determine app styling - colors, font - related Bootstrap info

### ISSUE THREAD

**Issue by darylnauman** [chingu-voyages/v36-geckos-team-07#40]
**__Task Description__**
- [ ] Determine app colors, font(s), etc.
- [ ] If using Bootstrap what setting do we need to use in our components and pages
- [ ] Update CSS file as needed?

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.
